/* Use Join */
SELECT CITY.NAME
FROM CITY
LEFT OUTER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Africa';


/* USE Subquery */
SELECT NAME 
FROM CITY
WHERE COUNTRYCODE IN
(SELECT CODE FROM COUNTRY 
 WHERE CONTINENT = 'Africa');