-- using Inner join
SELECT SUM(CITY.POPULATION)
FROM CITY 
INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Asia';


-- using subquery
SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE IN (SELECT CODE FROM COUNTRY
WHERE CONTINENT='Asia');